//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KhachSanEntities : DbContext
    {
        public KhachSanEntities()
            : base("name=KhachSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_CT_DP> tb_CT_DP { get; set; }
        public virtual DbSet<tb_datphong> tb_datphong { get; set; }
        public virtual DbSet<tb_DP_HH_DV> tb_DP_HH_DV { get; set; }
        public virtual DbSet<tb_func> tb_func { get; set; }
        public virtual DbSet<tb_hanghoa_dichvu> tb_hanghoa_dichvu { get; set; }
        public virtual DbSet<tb_khachhang> tb_khachhang { get; set; }
        public virtual DbSet<tb_loaiphong> tb_loaiphong { get; set; }
        public virtual DbSet<tb_nhacungcap> tb_nhacungcap { get; set; }
        public virtual DbSet<tb_nhanvien> tb_nhanvien { get; set; }
        public virtual DbSet<tb_phong> tb_phong { get; set; }
        public virtual DbSet<tb_tang> tb_tang { get; set; }
        public virtual DbSet<tb_thietbi> tb_thietbi { get; set; }
    }
}
