//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CT_DP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_CT_DP()
        {
            this.tb_DP_HH_DV = new HashSet<tb_DP_HH_DV>();
        }
    
        public int MaCT_DP { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> SoNgayO { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> MaDat { get; set; }
    
        public virtual tb_datphong tb_datphong { get; set; }
        public virtual tb_phong tb_phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DP_HH_DV> tb_DP_HH_DV { get; set; }
    }
}
