//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_hanghoa_dichvu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_hanghoa_dichvu()
        {
            this.tb_DP_HH_DV = new HashSet<tb_DP_HH_DV>();
        }
    
        public int MaHH_DV { get; set; }
        public string TenHH_DV { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DP_HH_DV> tb_DP_HH_DV { get; set; }
        public virtual tb_nhacungcap tb_nhacungcap { get; set; }
    }
}
