//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_loaiphong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_loaiphong()
        {
            this.tb_phong = new HashSet<tb_phong>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> SoGiuong { get; set; }
        public Nullable<int> SoNguoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_phong> tb_phong { get; set; }
    }
}
